### ISSUE TITLE
Readme Improvements

### ISSUE THREAD

**Issue by mohitjaisal** [mohitjaisal/Syncode#1]
- Mention contribution guidelines
- Add more images and gifs to project it better
- Update new logos and UI of the readme

**Comment by BobinMathew** [comment]
Hi, can I work on this task

**Comment by mohitjaisal** [comment]
go ahead @BobinMathew

**Comment by Ayush-Kanduri** [comment]
Hey Mohit.
I can improve the README a bit more.

Could you please assign the issue to me?

**Comment by Titanpimpale** [comment]
hi @mohitjaisal this is my first open source project can you assign me  readme flie improvement issue?

**Comment by mohitjaisal** [comment]
> Hey Mohit. I can improve the README a bit more.
> 
> Could you please assign the issue to me?

If you think you can do it in a better way, @Ayush-Kanduri  go ahead 👍🏻

**Comment by Ayush-Kanduri** [comment]
> > Hey Mohit. I can improve the README a bit more.
> > Could you please assign the issue to me?
> 
> If you think you can do it in a better way, @Ayush-Kanduri go ahead 👍🏻

Thanks, Mohit for assigning the issue. I'll try to do it with my style if you like it then you can merge it 😀

**Comment by Ayush-Kanduri** [comment]
Hi Mohit, I have made PR #5 to solve this issue. 

Kindly Merge the PR. 
I would be glad.

**Comment by mohitjaisal** [comment]
> Hi Mohit, I have made PR #5 to solve this issue.
> 
> Kindly Merge the PR. I would be glad.

There was some conflicts will look into that soon

**Comment by Ayush-Kanduri** [comment]
While creating the PR there were no conflicts at that time. 

Anyways, no issues.
I'll wait for the update 😁

**Comment by Ayush-Kanduri** [comment]
Hi Mohit, could you please Merge the PR? It will count towards Hacktoberfest.

**Comment by Ayush-Kanduri** [comment]
I have put a lot of effort and time into this. It would be nice if you approved it.
